# These are supported funding model platforms
# Do you like LaserGRBL? Support development with your donation!

custom: https://www.paypal.com/donate?business=4WQX8HUBXRVUU&no_recurring=0&item_name=LaserGRBL&currency_code=EUR
