//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBL {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserGRBL.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Right click here to add custom buttons.
        /// </summary>
        internal static string AddCustomButtonsHint {
            get {
                return ResourceManager.GetString("AddCustomButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abort current job?.
        /// </summary>
        internal static string BoxAbortProgramConfirm {
            get {
                return ResourceManager.GetString("BoxAbortProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatic update failed!
        ///Please manually download the new version from lasergrbl site..
        /// </summary>
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update require administrator privilege!.
        /// </summary>
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update result.
        /// </summary>
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update success!.
        /// </summary>
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are some changes that have not been applied.
        ///Do you want to rewrite the configuration?.
        /// </summary>
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Changes detected!.
        /// </summary>
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot connect to device.
        /// </summary>
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide GCode commands.
        /// </summary>
        internal static string BoxCustomButtonPleaseGCodeText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseGCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide tooltip text.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Missing field.
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipTitle {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure to delete selected button?.
        /// </summary>
        internal static string BoxDeleteCustomButtonText {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete custom button.
        /// </summary>
        internal static string BoxDeleteCustomButtonTitle {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error exporting config!.
        /// </summary>
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File does not exist!.
        /// </summary>
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config exported successfully!.
        /// </summary>
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Success.
        /// </summary>
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error reading file!.
        /// </summary>
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config imported with {1} errors!.
        /// </summary>
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config imported successfully!.
        /// </summary>
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import custom button.
        /// </summary>
        internal static string BoxImportCustomButtonCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove actual buttons? Select yes to remove, no to keep..
        /// </summary>
        internal static string BoxImportCustomButtonClearText {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmation.
        /// </summary>
        internal static string BoxImportCustomButtonrCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The engraver has some configuration parameters out of range. Please check machine configuration (menu &quot;Grbl&quot;, &quot;Grbl Configuration&quot;) parameters 130 and 131..
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeText {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeTitle {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error reading config!.
        /// </summary>
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Showing cached values....
        /// </summary>
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config read successfully!.
        /// </summary>
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Test notification has been sent, please check your phone!.
        /// </summary>
        internal static string BoxTelegramSettingText {
            get {
                return ResourceManager.GetString("BoxTelegramSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telegram notification.
        /// </summary>
        internal static string BoxTelegramSettingTitle {
            get {
                return ResourceManager.GetString("BoxTelegramSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No changes... nothing to write!.
        /// </summary>
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config written with {1} errors!.
        /// </summary>
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Config written successfully!.
        /// </summary>
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connect.
        /// </summary>
        internal static string BtnConnectTT {
            get {
                return ResourceManager.GetString("BtnConnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disconnect.
        /// </summary>
        internal static string BtnDisconnectTT {
            get {
                return ResourceManager.GetString("BtnDisconnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit button.
        /// </summary>
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove button.
        /// </summary>
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diagonal (old).
        /// </summary>
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horizontal (old).
        /// </summary>
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cross Fill.
        /// </summary>
        internal static string DirectionNewCross {
            get {
                return ResourceManager.GetString("DirectionNewCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diagonal.
        /// </summary>
        internal static string DirectionNewDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diagonal Cross Fill.
        /// </summary>
        internal static string DirectionNewDiagonalCross {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diagonal Grid.
        /// </summary>
        internal static string DirectionNewDiagonalGrid {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grid.
        /// </summary>
        internal static string DirectionNewGrid {
            get {
                return ResourceManager.GetString("DirectionNewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hilbert.
        /// </summary>
        internal static string DirectionNewHilbert {
            get {
                return ResourceManager.GetString("DirectionNewHilbert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horizontal.
        /// </summary>
        internal static string DirectionNewHorizontal {
            get {
                return ResourceManager.GetString("DirectionNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inset Filling.
        /// </summary>
        internal static string DirectionNewInsetFilling {
            get {
                return ResourceManager.GetString("DirectionNewInsetFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diagonal Reversed.
        /// </summary>
        internal static string DirectionNewReverseDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewReverseDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Squares.
        /// </summary>
        internal static string DirectionNewSquares {
            get {
                return ResourceManager.GetString("DirectionNewSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical.
        /// </summary>
        internal static string DirectionNewVertical {
            get {
                return ResourceManager.GetString("DirectionNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zig Zag.
        /// </summary>
        internal static string DirectionNewZigZag {
            get {
                return ResourceManager.GetString("DirectionNewZigZag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No Filling.
        /// </summary>
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical (old).
        /// </summary>
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File transfer in progress. Disconnect anyway?.
        /// </summary>
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dithering Options.
        /// </summary>
        internal static string DitheringOptions {
            get {
                return ResourceManager.GetString("DitheringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File transfer in progress. Exit anyway?.
        /// </summary>
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart required.
        /// </summary>
        internal static string FirmwareRequireRestart {
            get {
                return ResourceManager.GetString("FirmwareRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart is required to apply Firmware type changes. Restart now?.
        /// </summary>
        internal static string FirmwareRequireRestartNow {
            get {
                return ResourceManager.GetString("FirmwareRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custom.
        /// </summary>
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OpticalCorrect.
        /// </summary>
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SimpleAverage.
        /// </summary>
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WeightAverage.
        /// </summary>
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smooth (HQ Bicubic).
        /// </summary>
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sharp (NearestNeighbor).
        /// </summary>
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart required.
        /// </summary>
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Require application restart, restart now?.
        /// </summary>
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line To Line Options.
        /// </summary>
        internal static string Line2LineOptions {
            get {
                return ResourceManager.GetString("Line2LineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alarm.
        /// </summary>
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Check.
        /// </summary>
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connecting.
        /// </summary>
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disconnected.
        /// </summary>
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Door.
        /// </summary>
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hold.
        /// </summary>
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idle.
        /// </summary>
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jog.
        /// </summary>
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run.
        /// </summary>
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown.
        /// </summary>
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estimated Time:.
        /// </summary>
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projected Time:.
        /// </summary>
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot open a new file now..
        /// </summary>
        internal static string MsgboxCannotOpenFileNow {
            get {
                return ResourceManager.GetString("MsgboxCannotOpenFileNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error connecting your engraver.
        ///If you need help click on &quot;?&quot; button..
        /// </summary>
        internal static string ProblemConnectingText {
            get {
                return ResourceManager.GetString("ProblemConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problem with connection?.
        /// </summary>
        internal static string ProblemConnectingTitle {
            get {
                return ResourceManager.GetString("ProblemConnectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It seems that the current position is no longer known by Grbl.
        ///Without the Homing Procedure ($H) the result may not be reliable.
        ///Continue anyway?.
        /// </summary>
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown position.
        /// </summary>
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Speed:.
        /// </summary>
        internal static string SpeedSliderToolTip {
            get {
                return ResourceManager.GetString("SpeedSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Step:.
        /// </summary>
        internal static string StepSliderToolTip {
            get {
                return ResourceManager.GetString("StepSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This file type is not supported..
        /// </summary>
        internal static string UnsupportedFiletype {
            get {
                return ResourceManager.GetString("UnsupportedFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If the buffer is blocked, it is because there was some communication problem with your engraver. If you press &quot;OK&quot; LaserGRBL will ignore the full buffer and send the next commands. If this happens often, you should try to understand the causes of this problem.
        ///Click &quot;?&quot; for more information..
        /// </summary>
        internal static string WarnBufferStuckUnlockText {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unlock buffer.
        /// </summary>
        internal static string WarnBufferStuckUnlockTitle {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Centerline option is not compatible with your PC.
        ///64bit OS is needed!.
        /// </summary>
        internal static string WarnCenterline64bit {
            get {
                return ResourceManager.GetString("WarnCenterline64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line2Line option is not compatible with your engraver or with your configuration. PWM-able laser is needed, and PWM support should be enabled in LaserGRBL settings..
        /// </summary>
        internal static string WarnLine2LinePWM {
            get {
                return ResourceManager.GetString("WarnLine2LinePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string WarnMessageBoxHeader {
            get {
                return ResourceManager.GetString("WarnMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You have set negative offsets, but your engraver is set to use positive space with soft limit alarm enabled ($20=1).
        ///
        ///This could generate a soft-limit error. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitNS {
            get {
                return ResourceManager.GetString("WarnSoftLimitNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You have set a size and offset that makes the job larger than the workspace configured in your engraver ({0}mm x {1}mm).
        ///Grbl Parameters $130 and $131.
        ///
        ///This could generate a soft-limit error or the machine could crash into the axes boundary. Are you sure of the entered values?.
        /// </summary>
        internal static string WarnSoftLimitOOB {
            get {
                return ResourceManager.GetString("WarnSoftLimitOOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Job boundary confirmation.
        /// </summary>
        internal static string WarnSoftLimitTitle {
            get {
                return ResourceManager.GetString("WarnSoftLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Freely assigning the width and height of the work can lead to distortion of the image. Do you want to continue?.
        /// </summary>
        internal static string WarnUnlockProportionText {
            get {
                return ResourceManager.GetString("WarnUnlockProportionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string WarnUnlockProportionTitle {
            get {
                return ResourceManager.GetString("WarnUnlockProportionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;M4 Dynamic Laser Power Mode&quot; has been set, but your engraver doesn&apos;t seem to support it.
        ///Only engravers with grbl version &gt;= 1.1 with &quot;laser mode&quot; enabled ($32=1) can take advantage of M4 option..
        /// </summary>
        internal static string WarnWrongLaserMode {
            get {
                return ResourceManager.GetString("WarnWrongLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string WarnWrongLaserModeTitle {
            get {
                return ResourceManager.GetString("WarnWrongLaserModeTitle", resourceCulture);
            }
        }
    }
}
